project_id = "ghtcnebhrxyrxepufmed"

[functions.teaser]
verify_jwt = false

[functions.full-analysis]
verify_jwt = false

[functions.test-analyzer]
verify_jwt = false

[functions.screening-phase1]
verify_jwt = false

[functions.screening-phase2]
verify_jwt = false

[functions.screening-phase3]
verify_jwt = false

[functions.screening-teaser]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.publish-scheduled-articles]
verify_jwt = false
